[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.8.0-pre.0"
rand = "0.8"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "my_benchmark"
harness = false